version: '3'

services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    volumes:
      - .:/app
    working_dir: /app
    ports: 
      - 8000:8000
    networks:
      - dev
    depends_on:
      - db

  db:
    image: mdillon/postgis:11-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=feira
    networks:
      - dev

networks:
  dev: